# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-30 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
        ('movies', '0002_auto_20181203_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_data',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='landing.MovieData'),
            preserve_default=False,
        ),
    ]
