# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-30 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('movieid', models.IntegerField(blank=True, db_column='movieId', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('genres', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'movie_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('writers', models.CharField(blank=True, max_length=2000, null=True)),
                ('stars', models.CharField(blank=True, max_length=2000, null=True)),
                ('director', models.CharField(blank=True, max_length=2000, null=True)),
                ('runtime', models.CharField(blank=True, max_length=2000, null=True)),
                ('images', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
    ]
